.TH "disnix-gendist-roundrobin" "8" "June 2009" "Disnix" "System administration tools"
.SH NAME
disnix\-gendist\-roundrobin \- Generate a distribution expression from a service and infrastructure model 
.SH SYNOPSIS
.B disnix\-build
\-s services_expr \-i infrastructure_expr
.PP
.SH DESCRIPTION
The command \fBdisnix\-gendist\-roundrobin\fR generate a distribution expression from a given
services and infrastructure expression. It uses the round robin scheduling method to distribute every
service in the services model over each machine in the infrastructure in equal proportions and order.
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-services\fR
Provide a services model, which captures the components of a distributed system
.TP
\fB\-i\fR, \fB\-\-infrastructure\fR
Provide a infrastructure model, which captures properties of the machines in the network
.TP
\fB\-h\fR, \fB\-\-help\fR
Shows the usage of this command to the user
.SH AUTHOR
Sander van der Burg <s.vanderburg@tudelft.nl>
