.TH "disnix-distribute" "8" "June 2009" "Disnix" "System administration tools"
.SH NAME
disnix\-distribute \- Distributes intra-dependency closures of services to target machines
.SH SYNOPSIS
.B disnix\-distribute
[
.B options
]
manifest
.PP
.SH DESCRIPTION
The command \fBdisnix\-distribute\fR copies all the intra-dependency closures of services
in a manifest file to the target machines in the network. This process is very efficient,
since it scans for all intra-dependencies and only copies the missing parts.
.PP
Most users don't need to use this command directly. The \fBdisnix\-env\fR command will
automatically invoke this command to distribute the services if necessary.
.SH OPTIONS
.TP
\fB\-\-interface\fR
Path to executable that communicates with a Disnix interface. Defaults to \fBdisnix-ssh-client\fR
.TP
\fB\-h\fR, \fB\-\-help\fR
Shows the usage of this command to the user
.SH ENVIRONMENT VARIABLES
.TP
\fBDISNIX_CLIENT_INTERFACE\fR
Sets the client interface (which defaults to \fBdisnix-ssh-client\fR)
.SH SEE ALSO
.BR disnix-copy-closure (8),
.BR disnix-env (8)
.SH AUTHOR
Sander van der Burg <s.vanderburg@tudelft.nl>
