.TH "disnix-build" "8" "June 2009" "Disnix" "System administration tools"
.SH NAME
disnix\-build \- Build a combination of Disnix models
.SH SYNOPSIS
.B disnix\-build
\-s services_expr \-i infrastructure_expr \-d distribution_expr
[
.B options
]
.PP
.SH DESCRIPTION
The command \fBdisnix\-build\fR builds the derivations described by the three Disnix models that capture
concerns of the deployment of a distributed system, which are the services, infrastructure and distribution
expressions. If the build succeeds, it places a symlink to the result in the current directory. The symlink is
called result.
.PP
The services expression captures all the components of the distributed system. The infrastructure model captures
properties of the machines in the network. The distribution model maps the services from the services to the machines
in the infrastructure model.
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-services\fR
Provide a services model, which captures the components of a distributed system
.TP
\fB\-i\fR, \fB\-\-infrastructure\fR
Provide a infrastructure model, which captures properties of the machines in the network
.TP
\fB\-d\fR, \fB\-\-distribution\fR
Provide a distribution model, which maps services to machines
.TP
\fB\-h\fR, \fB\-\-help\fR
Shows the usage of this command to the user
.SH AUTHOR
Sander van der Burg <s.vanderburg@tudelft.nl>
